# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- development

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
   includePreviewVersions: true
   version: 6.x

- task: DotNetCoreCLI@2
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  inputs:
   command: build
   arguments: --configuration $(BuildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
   command: publish
   arguments: --configuration $(BuildConfiguration) --output publish_output
   zipAfterPublish: true


- task: CopyFiles@2
  inputs:
    SourceFolder: publish_output
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


